package exirium.pe.authflowapp.data.exception

class UsersException(message: String) : Exception(message)